package pjvsemproj.dto;

import pjvsemproj.models.entities.cities.City;

/**
 * Data Transfer Object representing settlement and city node assets.
 * <p>
 * Extends {@link EntityDTO} to capture structural properties specific to cities, including upgrade levels,
 * production metrics, and unit recruitment initialization authorization flags.
 */
public class CityDTO extends EntityDTO {
    public String cityLevel;
    // adding transient to tell Gson to not serialize it
    public transient int upgradePrice;
    public transient boolean canBeUpgraded;
    public transient int goldProducedPerRound;

    // Attribute shows if tile on which stands city is currently blocked or not
    public transient boolean canSpawnTroops;

    /**
     * Constructs a city data transfer container with complete structural parameter criteria.
     *
     * @param id                   The unique metadata string tracking token assigned to this specific city asset instance.
     * @param entityType           Descriptive label descriptor tracking the high-level system class layer (typically "City").
     * @param x                    The spatial grid coordinate position along the horizontal column map axis.
     * @param y                    The spatial grid coordinate position along the vertical row map axis.
     * @param ownerName            The distinct profile username matching the player who commands this settlement (or "Neutral").
     * @param cityLevel            The specific structural tier state identifier representing the level ranking of this city.
     * @param upgradePrice         The baseline financial gold cost necessary to advance this city to its subsequent development tier.
     * @param canBeUpgraded        Flag detailing whether this settlement can undergo a tier upgrade given economic or structural rules.
     * @param goldProducedPerRound The amount of economic currency generated by this city during turn transition intervals.
     * @param canSpawnTroops       Flag specifying whether the underlying grid tile is clear for unit recruitment operations.
     */
    public CityDTO(
            String id, String entityType, int x, int y, String ownerName,
            String cityLevel, int upgradePrice,
            boolean canBeUpgraded, int goldProducedPerRound,
            boolean canSpawnTroops
    ) {
        super(id, entityType, x, y, ownerName);
        this.cityLevel = cityLevel;
        this.upgradePrice = upgradePrice;
        this.canBeUpgraded = canBeUpgraded;
        this.goldProducedPerRound = goldProducedPerRound;
        this.canSpawnTroops = canSpawnTroops;
    }

    /**
     * Contextual hydration constructor that maps live domain models directly into safe transfer representations.
     * <p>
     * Resolves parent class metrics, translates enum types, evaluates economic production balances,
     * and performs layout obstruction checks across the surrounding grid map space.
     *
     * @param city The live active {@link City} domain object instance to extract snapshot state parameters from.
     */
    public CityDTO(City city) {
        super(
                city.getId(),
                "City",
                city.getTile().getX(),
                city.getTile().getY(),
                city.getOwner() != null ? city.getOwner().getName() : "Neutral"
        );

        this.cityLevel = city.getCityType().name();
        this.upgradePrice = city.getUpgradePrice();
        this.canBeUpgraded = city.canBeUpgraded();
        this.goldProducedPerRound = city.getGoldProducedPerRound();
        this.canSpawnTroops = !city.getTile().isBlocked();
    }
}